export const UPLOAD_DIRECTORY = 'uploads/'
export const HOTELS_DIRECTORY = 'hotels/'
export const PROGRAMS_DIRECTORY = 'programs/'
export const USER_DIRECTORY = 'users/'
export const COMPANIES_DIRECTORY = 'companies/'
