import { Router } from "express";
import transportationsRoutes from "./transportations.routes";
import hotelsRoutes from "./hotels.routes";
import countriesRoutes from "./countries.routes";
import groupsRoutes from "./groups.routes";
import authRoutes from "./auth.routes";
const router = Router();
router.use("/transportations", transportationsRoutes);
router.use("/hotels", hotelsRoutes);
router.use("/countries", countriesRoutes);
router.use("/groups", groupsRoutes);
router.use("/auth", authRoutes);
export default router;
