import { Router } from "express";
import transportationsRoutes from "./transportations.routes";
import hotelsRoutes from "./hotels.routes";
import countriesRoutes from "./countries.routes";
import groupsRoutes from "./groups.routes";
import authRoutes from "./auth.routes";
import userRoutes from "./user.routes";
import companiesRoutes from "./companies.routes";
import notificationsRoutes from "./notifications.routes";
import chatRoutes from "./chat.routes";
const router = Router();
router.use("/transportations", transportationsRoutes);
router.use("/hotels", hotelsRoutes);
router.use("/countries", countriesRoutes);
router.use("/groups", groupsRoutes);
router.use("/auth", authRoutes);
router.use("/user", userRoutes);
router.use("/companies", companiesRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/chats", chatRoutes);
export default router;
